name: Erlang CI

on:
  push:
  pull_request:

jobs:

  build:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        erlang: [ 21,22,23,24 ]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v2
    - run: make compile

  verify:
    runs-on: ubuntu-latest
    strategy: 
      matrix:
        erlang: [ 21,22,23,24 ]

    container:
      image: erlang:${{ matrix.erlang }}

    steps:
    - uses: actions/checkout@v2
    - run: make dialyzer
